SET PATH=D:\Keil_v5\ARM\ARMCC\Bin;D:\Python27\;D:\Python27\Scripts;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\TortoiseSVN\bin;D:\Git\cmd;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Common Files\Autodesk Shared\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;D:\vc6.0\Tools\WinNT;D:\vc6.0\MSDev98\Bin;D:\vc6.0\Tools;D:\VC98\bin;D:\_Install\arduino-1.6.5-r5-windows\arduino-1.6.5-r5\hardware\tools\avr\bin
SET CPU_TYPE=STM32F103RC
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=Target 1
SET CPU_CLOCK=0x007A1200
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\main.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\stm32f10x_it.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\system_stm32f10x.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\usart.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\jamptoapp.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\misc.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\stm32f10x_gpio.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\stm32f10x_rcc.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\stm32f10x_usart.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\stm32f10x_dma.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\stm32f10x_adc.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\stm32f10x_flash.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\stm32f10x_wwdg.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\core_cm3.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmAsm" --Via "..\output\startup_stm32f10x_md._ia"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\delay.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\tft.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "..\output\led.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmLink" --Via "..\output\template.lnp"
